# Generated by Django 5.0.3 on 2024-03-16 21:59

import test.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingroom',
            name='code',
            field=models.CharField(default=test.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
